### ISSUE TITLE
Error al abrir Cap5_2_MUX.circ

### ISSUE THREAD

**Issue by abrahdev** [JesusSalido/CircsTecobook#1]
Problema al intentar abrir el archivo Cap5_2_MUX.circ en Logisim (v2.7.1).
Al cargar el archivo, aparece un mensaje de error indicando que falta el archivo func_MUX.circ, que parece ser requerido por la librería del proyecto.

[Cap5_2_MUX.circ](https://github.com/JesusSalido/CircsTecobook/blob/main/Teor%C3%ADa/Cap5_2_MUX.circ)
![Captura de pantalla 2024-10-25 144203](https://github.com/user-attachments/assets/464a4e51-378e-40f3-b4bb-3a5753b2a092)

**Comment by JesusSalido** [comment]
Creo que se ha solucionado. Era una inconsistencia relacionada con una versión previa de los circuitos.
Comprobar si se ha resuelto.

**Comment by abrahdev** [comment]
Ya funciona, muchas gracias.
